dist: trusty
sudo: required

language: node_js
node_js: 9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_install:
  - stty cols 80

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - fluxbox >/dev/null 2>&1 &

script: npm run test:ci